version: 2
jobs:
   build:
     docker:
       - image: google/cloud-sdk:latest
     steps:
       - checkout
       - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
       - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
       - run: gcloud config set project $GCLOUD_PROJECT
       - run: ./make-image.sh
